BackEnd pull request
etsy-FEC-project/hrsf93-front-end-capstone-image-side pull request #1
Opened 2018-04-17 22:02 UTC by ahmadaladdasi

Created DB, Seeded DB with 100 fake records, created server GET and POST routes and tested them with POSTMAN

2018-04-18 00:22 UTC, samliebow requested changes
1. Why are you using airbnb-base rather than airbnb for the eslint config?  From some cursory research, it looks like that's for if you're *not* using React.  _Fixed_
2. In your package.json, ' "eslint-config-hackreactor": "airbnb-base" ' doesn't seem to make sense - and it broke when I tried to run npm install. What's this doing? _Fixed_
3. I don't understand your post handler - is it supposed to add an image to the listing, or create a set of images for a new listing? Why does it send back the data it was given, and why does it do so synchronously (before you know if the save was actually successful)? _Let's discuss this_
4. The way you import from database/index.js is confusing - you're exporting several methods in an object and calling that object 'db', which made me think that it was actually the database connection (like in the Mongoose example: http://mongoosejs.com/docs/index.html). _rename it ?_
5. Is each record a single image or is it a group of images associated with a listing? The names "imageSchema" and "Picture" (which should be consistent, btw) make me think it's one image, but there's an array of urls for each one. _rename it to be pictureSchema_
6. The way you're seeding your database is very odd - you're creating an array of a single item, calling 'forEach' on that one-item array, saving that one item, and then repeating that process a hundred times. You should just put all the objects in a single array and use Picture.create(arrayName) once. This also eliminates the need to use 'const foo = new Picture({})' followed by 'foo.save()' - create does both in one step. _Let's discuss_
7. Rather than exporting functions that use your model's methods, you should probably just export your model and use its methods directly. _let's discuss_

Minor points:
1. In your database schema, I'm not sure what 'index: true' for your id property gets you (besides that bug you were having). This isn't necessarily wrong - I just don't know what it's useful for. _removed_
2. I'm guessing you installed the airbnb eslint config globally. You should consider installing it locally in your repo too, since anyone who wants to fork or clone your repo (e.g. me) will have to install the config themselves otherwise. _fixed_
3. You may want to set up jest --watch and jest --coverage as npm scripts. 
4. What's the urlencoded body parser doing in your server? Do you use that for anything? _i got some JSON circular errors, this seemed to fixed app/json encoding issues_
5. Delete the leftover comment in database/index.js on line 6. _Done_

I like the use of variables for directories in your webpack config.

2018-04-19 01:44 UTC, ahmadaladdasi commented
@samliebow ,  I updated the pull request per your comments

2018-04-19 02:00 UTC, samliebow commented
Much improved! The one thing I'd watch out for is the use of .catch - I'm not sure one way or the other whether that's supported by Mongoose, since Mongoose doesn't do regular promises (see http://mongoosejs.com/docs/promises.html). But if you want to keep that, you could easily enough swap out Mongoose's promise implementation with e.g. Bluebird (see that same link), or just use (success, error) => {} in your .then blocks. 

I think you're pretty much good to go here.

2018-04-19 02:00 UTC, samliebow approved these changes

2018-04-19 02:25 UTC, merged